### ISSUE TITLE
Wrong quote parsing in nicknames

### ISSUE THREAD

**Issue by Eiyeron** [juju2143/walrusirc#5]
The title says all. If one user have quotes/double quotes in the nickname, they're wrongly escaped into html code

> Duke "Eiyeron" tape

Will be converted to

> Duke &quot;Tape&quot; Eiyeron

**Comment by juju2143** [comment]
The nickname is escaped twice, once by SMF and once by the WalrusIRC client. The same bug also happens in OmnomIRC and is even part of the protocol specification. I already have some sort of fix on the client (that I should commit soon), but @Sorunome suggested it should be done at the checkLogin.php level (that is, unescaping it there and re-escaping it in the client), so I guess we'll see what he will do.

**Comment by juju2143** [comment]
Sorunome/OmnomIRC2@2ed8bbc6000fe3bb6069aeb8da772d05406062a4 is probably gonna fix it, so I won't bother commiting that change for now.
